CREATE TABLE APPLICATION_COMPONENTS (
       APPLICATION_NAME     VARCHAR(30) NOT NULL,
       SUBJECT_AREA         VARCHAR(30) NOT NULL,
       DESCRIPTION          VARCHAR(60) NOT NULL
);

CREATE UNIQUE INDEX XPKAPPLICATION_COMPONENTS ON APPLICATION_COMPONENTS
(
       APPLICATION_NAME               ASC,
       SUBJECT_AREA                   ASC
);

ALTER TABLE APPLICATION_COMPONENTS
       ADD  (  CONSTRAINT XPKAPPLICATION_COMPONENTS PRIMARY KEY (APPLICATION_NAME, SUBJECT_AREA) ) ;

CREATE TABLE APPLICATION_MASTER (
       APPLICATION_NAME     VARCHAR(30) NOT NULL,
       DESCRIPTION          VARCHAR(60) NULL
);

CREATE UNIQUE INDEX APPMAS_PK ON APPLICATION_MASTER
(
       APPLICATION_NAME               ASC
);


ALTER TABLE APPLICATION_MASTER
       ADD  (  CONSTRAINT APPMAS_PK PRIMARY KEY (APPLICATION_NAME) ) ;


CREATE TABLE GLOBAL_OPTIONS (
       APPLICATION_NAME     VARCHAR(30) NOT NULL,
       MODULE_TYPE_CODE     VARCHAR(8) NOT NULL,
       FILE_NAME            VARCHAR(30) NULL,
       GRAPHIC_TYPE         VARCHAR(8) NULL,
       LOGO_TITLE           VARCHAR(8) NULL
);

CREATE UNIQUE INDEX GLOBOPT_PK ON GLOBAL_OPTIONS
(
       APPLICATION_NAME               ASC,
       MODULE_TYPE_CODE               ASC
);


ALTER TABLE GLOBAL_OPTIONS
       ADD  (  CONSTRAINT GLOBOPT_PK PRIMARY KEY (APPLICATION_NAME, MODULE_TYPE_CODE) ) ;

CREATE UNIQUE INDEX GLOBOPT_PK ON GLOBAL_OPTIONS
(
       APPLICATION_NAME               ASC,
       MODULE_TYPE_CODE               ASC
);


ALTER TABLE GLOBAL_OPTIONS
       ADD  (  CONSTRAINT GLOBOPT_PK PRIMARY KEY (APPLICATION_NAME, MODULE_TYPE_CODE) ) ;


CREATE TABLE MESSAGE_MASTER (
       MESSAGE_ID           INTEGER NOT NULL,
       MESSAGE_CODE         VARCHAR(8) NOT NULL,
       MESSAGE_SOURCE       VARCHAR(8) NOT NULL,
       APPLICATION_NAME     VARCHAR(30) NOT NULL,
       MESSAGE_TEXT         VARCHAR(80) NOT NULL,
       MESSAGE_HELP         VARCHAR(240) NOT NULL,
       MESSAGE_TYPE_IND     VARCHAR(1) NOT NULL,
       AUDIT_FLAG           VARCHAR(1) NOT NULL,
       RESPONSE_ROUTING     VARCHAR(30) NULL,
       CREATED_BY           VARCHAR(30) NOT NULL,
       DATE_CREATED         DATE NOT NULL,
       LAST_UPDATE_BY       VARCHAR(30) NULL,
       LAST_UPDATE          DATE NULL
);

CREATE UNIQUE INDEX MSGMAS_PK ON MESSAGE_MASTER
(
       MESSAGE_ID                     ASC
);

CREATE UNIQUE INDEX XAK1MESSAGE_MASTER ON MESSAGE_MASTER
(
       APPLICATION_NAME               ASC,
       MESSAGE_SOURCE                 ASC,
       MESSAGE_CODE                   ASC
);


ALTER TABLE MESSAGE_MASTER
       ADD  (  CONSTRAINT MSGMAS_PK PRIMARY KEY (MESSAGE_ID) ) ;


CREATE TABLE MODULE_MASTER (
       MODULE_NAME          VARCHAR(8) NOT NULL,
       MODULE_TYPE_CODE     VARCHAR(10) NOT NULL,
       DESCRIPTION          VARCHAR(60) NOT NULL,
       APPLICATION_NAME     VARCHAR(30) NOT NULL,
       RECORD_BY            VARCHAR(30) NOT NULL,
       RECORD_DATE          DATE NOT NULL,
       MODULE_SOURCE_PATH   VARCHAR(80) NULL,
       MODULE_EXECUTABLE_PATH VARCHAR(80) NULL,
       MODIFIED_BY          VARCHAR(30) NULL,
       MODIFICATION_DATE    DATE NULL
);

CREATE UNIQUE INDEX MODMAS_PK ON MODULE_MASTER
(
       MODULE_NAME                    ASC
);


ALTER TABLE MODULE_MASTER
       ADD  (  CONSTRAINT MODMAS_PK PRIMARY KEY (MODULE_NAME) ) ;


CREATE TABLE MODULE_NETWORK_MASTER (
       PARENT_MODULE        VARCHAR(8) NOT NULL,
       CHILD_MODULE         VARCHAR(8) NOT NULL,
       CALLING_METHOD_IND   VARCHAR(1) NOT NULL
);

CREATE UNIQUE INDEX MODNET_PK ON MODULE_NETWORK_MASTER
(
       PARENT_MODULE                  ASC,
       CHILD_MODULE                   ASC
);


ALTER TABLE MODULE_NETWORK_MASTER
       ADD  (  CONSTRAINT MODNET_PK PRIMARY KEY (PARENT_MODULE, CHILD_MODULE) ) ;


CREATE TABLE ROLE_MODULE_DETAILS (
       ROLE_ID              INTEGER NOT NULL,
       MODULE_NAME          VARCHAR(8) NOT NULL,
       AREA_NAME            VARCHAR(30) NOT NULL,
       ITEM_NAME            VARCHAR(30) NOT NULL,
       ENABLED_FLAG         VARCHAR(1) NOT NULL,
       SECURE_FLAG          VARCHAR(1) NULL,
       QUERY_ONLY           VARCHAR(1) NOT NULL,
       UPDATE_FLAG          VARCHAR(1) NOT NULL,
       RECORD_BY            VARCHAR(30) NOT NULL,
       RECORD_DATE          DATE NOT NULL,
       MODIFIED_BY          VARCHAR(30) NULL,
       MODIFICATION_DATE    DATE NULL
);

CREATE UNIQUE INDEX RMDET_PK ON ROLE_MODULE_DETAILS
(
       ROLE_ID                        ASC,
       MODULE_NAME                    ASC,
       AREA_NAME                      ASC,
       ITEM_NAME                      ASC
);


ALTER TABLE ROLE_MODULE_DETAILS
       ADD  (  CONSTRAINT RMDET_PK PRIMARY KEY (ROLE_ID, MODULE_NAME, AREA_NAME, ITEM_NAME) ) ;


CREATE TABLE ROLE_MODULES (
       ROLE_ID              INTEGER NOT NULL,
       MODULE_NAME          VARCHAR(8) NOT NULL,
       INSERT_ALLOWED_FLAG  VARCHAR(1) NOT NULL,
       UPDATE_ALLOWED_FLAG  VARCHAR(1) NOT NULL,
       DELETE_ALLOWED_FLAG  VARCHAR(1) NOT NULL,
       QUERY_ONLY           VARCHAR(1) NOT NULL,
       RECORD_BY            VARCHAR(30) NOT NULL,
       RECORD_DATE          DATE NOT NULL,
       MODIFIED_BY          VARCHAR(30) NULL,
       MODIFICATION_DATE    DATE NULL
);

CREATE UNIQUE INDEX RMOD_PK ON ROLE_MODULES
(
       ROLE_ID                        ASC,
       MODULE_NAME                    ASC
);


ALTER TABLE ROLE_MODULES
       ADD  (  CONSTRAINT RMOD_PK PRIMARY KEY (ROLE_ID, MODULE_NAME) ) ;

CREATE TABLE USER_CONFIG_OPTION_DETAILS (
       USER_ID              INTEGER NOT NULL,
       APP_TYPE             VARCHAR(30) NOT NULL,
       APP_NAME             VARCHAR(30) NOT NULL,
       APP_FILESPEC         VARCHAR(60) NOT NULL
);

CREATE UNIQUE INDEX UCFGDET_PK ON USER_CONFIG_OPTION_DETAILS
(
       USER_ID                        ASC,
       APP_TYPE                       ASC
);


ALTER TABLE USER_CONFIG_OPTION_DETAILS
       ADD  (  CONSTRAINT UCFGDET_PK PRIMARY KEY (USER_ID, APP_TYPE) ) ;


CREATE TABLE USER_CONFIG_OPTIONS (
       USER_ID              INTEGER NOT NULL,
       RECORD_BY            VARCHAR(30) NOT NULL,
       RECORD_DATE          DATE NOT NULL,
       EXECUTION_PATH       VARCHAR(30) NULL,
       SOURCE_PATH          VARCHAR(30) NULL,
       BUTTON_X_POS         INTEGER NULL,
       BUTTON_Y_POS         integer NULL,
       BUTTONBAR_DIR        VARCHAR(30) NULL,
       MODIFIED_BY          VARCHAR(30) NULL,
       MODIFICATION_DATE    DATE NULL,
       LAST_ACCESS_MOD_BY   VARCHAR(30) NULL,
       LAST_ACCESS_MOD_DATE DATE NULL,
       BUTTON_BAR_SIZE_IND  VARCHAR(1) NULL
);

CREATE UNIQUE INDEX UCFG_PK ON USER_CONFIG_OPTIONS
(
       USER_ID                        ASC
);


ALTER TABLE USER_CONFIG_OPTIONS
       ADD  (  CONSTRAINT UCFG_PK PRIMARY KEY (USER_ID) ) ;


CREATE TABLE USER_MODULE_DETAILS (
       USER_ID              INTEGER NOT NULL,
       MODULE_NAME          VARCHAR(8) NOT NULL,
       AREA_NAME            VARCHAR(30) NOT NULL,
       ITEM_NAME            VARCHAR(30) NOT NULL,
       ENABLED_FLAG         VARCHAR(1) NOT NULL,
       SECURE_FLAG          VARCHAR(1) NULL,
       QUERY_ONLY_FLAG      VARCHAR(1) NOT NULL,
       UPDATE_FLAG          VARCHAR(1) NOT NULL,
       RECORD_BY            VARCHAR(30) NOT NULL,
       RECORD_DATE          DATE NOT NULL,
       MODIFIED_BY          VARCHAR(30) NULL,
       MODIFICATION_DATE    DATE NULL
);

CREATE UNIQUE INDEX UMDET_PK ON USER_MODULE_DETAILS
(
       USER_ID                        ASC,
       MODULE_NAME                    ASC,
       AREA_NAME                      ASC,
       ITEM_NAME                      ASC
);


ALTER TABLE USER_MODULE_DETAILS
       ADD  (  CONSTRAINT UMDET_PK PRIMARY KEY (USER_ID, MODULE_NAME, AREA_NAME, ITEM_NAME) ) ;


CREATE TABLE USER_MODULES (
       USER_ID              INTEGER NOT NULL,
       MODULE_NAME          VARCHAR(8) NOT NULL,
       INSERT_ALLOWED_FLAG  VARCHAR(1) NOT NULL,
       UPDATE_ALLOWED_FLAG  VARCHAR(1) NOT NULL,
       DELETE_ALLOWED_FLAG  VARCHAR(1) NOT NULL,
       QUERY_ONLY_FLAG      VARCHAR(1) NOT NULL,
       RECORD_BY            VARCHAR(30) NOT NULL,
       RECORD_DATE          DATE NOT NULL,
       MODIFIED_BY          VARCHAR(30) NULL,
       MODIFICATION_DATE    DATE NULL
);

CREATE UNIQUE INDEX UMOD_PK ON USER_MODULES
(
       USER_ID                        ASC,
       MODULE_NAME                    ASC
);


ALTER TABLE USER_MODULES
       ADD  (  CONSTRAINT UMOD_PK PRIMARY KEY (USER_ID, MODULE_NAME) ) ;


CREATE TABLE USER_OPTION_APPLICATION_TYPES (
       APP_TYPE             VARCHAR(30) NOT NULL
                                          CHECK (APP_TYPE in ('Y','N',NULL)),
       USER_UPDATE_FLAG     VARCHAR(1) NOT NULL
);

CREATE UNIQUE INDEX UOAT_PK ON USER_OPTION_APPLICATION_TYPES
(
       APP_TYPE                       ASC
);


ALTER TABLE USER_OPTION_APPLICATION_TYPES
       ADD  (  CONSTRAINT UOAT_PK PRIMARY KEY (APP_TYPE) ) ;

CREATE TABLE PERSON_CALENDARS (
       ID		             VARCHAR(30) NOT NULL,
       CALENDAR_ID           VARCHAR(30) NOT NULL,
	   CALENDAR_ID           VARCHAR(30) NOT NULL,
       ACTIVE_FLAG           CHAR(1) NOT NULL DEFAULT 'Y'
);