/*
14/05/201609:01:37 PM - tgray
*/
CREATE UNIQUE INDEX XPKAPPLICATION_COMPONENTS 
  ON APPLICATION_COMPONENTS (APPLICATION_NAME, SUBJECT_AREA);
CREATE UNIQUE INDEX APPMAS_PK 
  ON APPLICATION_MASTER (APPLICATION_NAME);
CREATE UNIQUE INDEX GLOBOPT_PK 
  ON GLOBAL_OPTIONS (APPLICATION_NAME, MODULE_TYPE_CODE);
CREATE UNIQUE INDEX XAK1MESSAGE_MASTER 
  ON MESSAGE_MASTER (APPLICATION_NAME, MESSAGE_SOURCE, MESSAGE_CODE);
CREATE UNIQUE INDEX MSGMAS_PK 
  ON MESSAGE_MASTER (MESSAGE_ID);
CREATE UNIQUE INDEX MODMAS_PK 
  ON MODULE_MASTER (MODULE_NAME);
CREATE UNIQUE INDEX MODNET_PK 
  ON MODULE_NETWORK_MASTER (PARENT_MODULE, CHILD_MODULE);
CREATE INDEX ADDRESS_ID 
  ON PERSON_ADDRESSES (ADDRESS_ID);
CREATE INDEX PERSON_ID 
  ON PERSON_ADDRESSES (PERSON_ID);
CREATE UNIQUE INDEX RMOD_PK 
  ON ROLE_MODULES (ROLE_ID, MODULE_NAME);
CREATE UNIQUE INDEX RMDET_PK 
  ON ROLE_MODULE_DETAILS (ROLE_ID, MODULE_NAME, AREA_NAME, ITEM_NAME);
CREATE UNIQUE INDEX UCFG_PK 
  ON USER_CONFIG_OPTIONS (USER_ID);
CREATE UNIQUE INDEX UCFGDET_PK 
  ON USER_CONFIG_OPTION_DETAILS (USER_ID, APP_TYPE);
CREATE UNIQUE INDEX UMOD_PK 
  ON USER_MODULES (USER_ID, MODULE_NAME);
CREATE UNIQUE INDEX UMDET_PK 
  ON USER_MODULE_DETAILS (USER_ID, MODULE_NAME, AREA_NAME, ITEM_NAME);
CREATE UNIQUE INDEX UOAT_PK 
  ON USER_OPTION_APPLICATION_TYPES (APP_TYPE);
